sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build -t sebassllr/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true sebassllr/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-778826954840"
    bucket_path: "docker"
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY