sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build -t sebassllr/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true sebassllr/docker-react npm run test